title: jhwaffles
description: "Assorted Projects and Posts"

url: "https://jhwaffles.github.io/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about

social:
  github: jhwaffles
  email: jwhuang88@gmail.com
  linkedin: justin-huang-6a10782b
#google_analytics: "UA-58263416-1"

#disqus:
#    shortname: brianmaierjr
